### PR TITLE
Refactor / clean up CMake configuration

### PR DESCRIPTION
**Pull request by PetrosKataras**
Hi,

I am putting this here for review, discussion and suggestions! I know that everything is in flux right now but I think it would be probably good to start discussing on something more concrete. The idea is to simplify as possible the config files by taking advantage of cmake functionality and also to remove duplicate parts.  

Main parts include the propagation of include and lib dependencies through appropriate cmake properties
so that you dont have to re-include what is already included with cinder.

The examples now can be part of the building process of cinder or separately by exporting `Cinder_DIR` and pointing to the directory where cinder was built ( this is illustrated in BasicApp ). This also allows for custom application directories and its made possible by using the export functionality of cmake. At some point it would be nice to add also an install target for cinder so that it can be installed in custom directories.

This version uses system installed libraries by using the `find_package` mechanism and has the `cbuilder` moved under `tools/linux` since it feels more natural next to the TinderBox directories. At least to me : )

Other than that cleanup, simplification and removal of duplicates. 

It would be great to hear some thoughts on this!
Cheers,
Petros

### CODE REVIEW

**Comment by ulyssesp** [comment]
I have some issues with finding boost on this branch that aren't the case on @chaoticbob's android branch (arch linux). It looks like `find_package` might be wonky?

**Comment by PetrosKataras** [comment]
Hi, thanks for checking this. It would help if we could see the config output that you get when running cmake. I suppose that you have boost-system and boost-filesystem installed in your system right? And not in a custom location? The FindBoost.cmake is provided by cmake by default so i would expect it to work if boost is installed on a non custom location. Also it would help to see the directory that boost is installed in your system.

**Comment by ulyssesp** [comment]
Oh interesting. It can't build from the boost libraries downloaded with Cinder. It's running the build properly after fetching `boost` from Arch's package manager. I'll let you know what the build output is.

**Comment by ulyssesp** [comment]
This is super close! The only tweak I had to make was `BOOST_LIBRARIES` => `Boost_LIBRARIES` (and `INCLUDE_DIRS` as well).

`BasicApp_d` still isn't working - it fails with `error: GLSL 1.50 is not supported` - but that's a problem for a different PR.

**Comment by PetrosKataras** [comment]
The whole idea of this work here on this branch is that it uses system wide installed libraries instead of the ones that ship with Cinder. You shouldn't need or try to manually define anything on your side since these variables are already defined once boost is found as you can see [here](https://github.com/PetrosKataras/Cinder/blob/linux-dev-chaotic/linux/CMakeLists.txt#L127-L128) . Also you can switch between system installed and cinder packaged sources with the `CINDER_USE_SYSTEM_INSTALLED_LIBS` which can be found [here](https://github.com/PetrosKataras/Cinder/blob/linux-dev-chaotic/linux/CMakeLists.txt#L121). 

The GL error seems to come because your hardware doesn't support modern OpenGL.

**Comment by ulyssesp** [comment]
Yup, I figured out that this PR is to make it use system libraries after your first comment. The `BOOST_LIBRARIES` suggestion was referring to `CMakeLists.txt` which is now fixed. Good stuff!

Originally I thought it was a hardware support issue too, but reading up on [the arch linux forums](https://bbs.archlinux.org/viewtopic.php?id=201864) and [the mesa site](http://www.mesa3d.org/shading.html)  and using `glxinfo` to confirm that 3.3 is available on my system makes it seem like an issue in context creation. [a forum post on the OpenGL forums](https://www.opengl.org/discussion_boards/showthread.php/184374-opengl-3-3-core-glsl-3-30-render-fails) has it working with these drivers on this graphics card. I think it has to do with the way that the cinder defines identifiers like `CINDER_MSW`, but I don't know enough about the Cinder codebase (yet) to have a fix for it. I'll keep on looking and any hints as to where to look would be greatly appreciated.

**Comment by PetrosKataras** [comment]
I know that @chaoticbob is currently working on fixing/refactoring and cleaning up some stuff so I would personally wait a bit before going really on detail about these kind of issues. We can come back to this when there is an update on the repo. Cheers!

**Pull request closed without merging**
